name: game_saves_backup
description: A linux application to backup game saves.
publish_to: 'none'
version: 0.0.3+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  intl:
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  file_selector: ^1.0.3
  url_launcher: ^6.3.1
  native_context_menu: ^0.2.2+5
  uuid: ^4.5.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.14
  path_provider:
  path:
  clock:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  arb_generator: ^0.0.4
  build_runner:
  riverpod_generator: ^2.6.3
  custom_lint:
  riverpod_lint: ^2.6.3
  app_store_screenshots:
    git: 
      url: https://github.com/defuncart/app_store_screenshots

flutter:
  uses-material-design: true
  generate: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: ""
  csv_settings:
    delimiter: ";"
    base_index: 1
